name: CI
on:
  push:
    branches: [main]
    tags: 
      - '*'
  pull_request:
permissions:
  contents: write
jobs:
  flatpak:
    name: "Flatpak"
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/flathub-infra/flatpak-github-actions:gnome-49
      options: --privileged
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
    - uses: flatpak/flatpak-github-actions/flatpak-builder@v6
      with:
        bundle: pwvucontrol.flatpak
        manifest-path: build-aux/com.saivert.pwvucontrol.json
        cache-key: flatpak-builder-${{ github.sha }}
    - name: Release
      uses: softprops/action-gh-release@v2
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: pwvucontrol.flatpak
